### register user
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name": "Yasin Memon",
    "email": "memonyasin121@gmail.com",
    "password": "1234"
}

### login user
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "memonyasin120@gmail.com",
    "password": "1234"
}

### logout user
POST http://localhost:3000/api/logout
Content-Type: application/json

### Get blogs
GET http://localhost:3000/api/blog

### create blogs
POST http://localhost:3000/api/blog/create
Content-type: "application/json"

{
    "title" : "Mekanism",
    "description" : "Learn Next.js"
}

### edit blog
PATCH  http://localhost:3000/api/blog/edit/6a156a42f5fbb98fca398dfb
Content-Type: application/json

{
    "title" : "MEKA",
    "description" : "edited blog"
}

### delete blog
DELETE http://localhost:3000/api/blog/delete/6a156a42f5fbb98fca398dfb